### ISSUE TITLE
Provide quick start instructions for the mobile app

### ISSUE THREAD

**Issue by Sevenarth** [healthyhomeuk/healthyhome#37]
Provide quick start instructions for the mobile app so that anybody can easily run and test it. This includes any requirements, relevant information and commands that are necessary to understand the process.

**Comment by amrllkmn** [comment]
Good idea. That would mean there's three ways of running it:

- On Expo:
    - Install Expo on their respective devices.
    - Open the mobile-app folder and run ```expo start```.
    - Scan QR code generated at the terminal or at the localhost.
    
- On iOS (requires a Macbook and a iOS device):
    - run command at the terminal at the ```mobile-app``` folder ```npm run ios```.
    
- On Android (Android device emulator or an Android device connected through USB):
    - run command ```npm run android``` at the terminal in the ```mobile-app``` folder.

Are these the right steps? Am I missing anything?

**Comment by roryort** [comment]
Closed with PR #69
