### ISSUE TITLE
Implement GitHub Actions

### ISSUE THREAD

**Issue by Sevenarth** [healthyhomeuk/healthyhome#45]
Implement GitHub Actions for building, testing and deploying.

- [x] Generic linter (https://github.com/github/super-linter)
- [ ] C++ test, lint and build
- [ ] JS docs test and generation
- [ ] JS testing
- [ ] Doxygen test and generation

**Comment by Sevenarth** [comment]
Generic linter as in [Super Linter](https://github.com/github/super-linter)

**Comment by roryort** [comment]
Closed due to non-usage of GitHub Actions
