### ISSUE TITLE
Plan monitoring server software architecture

### ISSUE THREAD

**Issue by Sevenarth** [healthyhomeuk/healthyhome#5]
The monitoring server requires an architectural plan before development. This can be performed through the use of UML, e.g. class diagrams.

Architectural requirements:
- **Platform-agnostic**: the monitoring server shall be agnostic to its host platform. Our prototype target is a Raspberry Pi, i.e. an ARM Linux target. Though, this should not represent a blocker from implementing the server on a baremetal target, e.g. ARMv7-M, for a more IoT-specific application;
- **Loosely coupled**: the monitoring server shall specify entity abstractions and provide an object registration process when needed. This will allow the monitoring server to:
    - be loosely tied to any possible sensor, hence rendering it sensor-agnostic as well. Any possible sensor should be allowed to be implemented;
    - ease its platform-agnosticism by abstracting away the implementation for any communication protocol. For example the I2C protocol, is implemented in different ways according to the platform. Linux uses file descriptors, embedded µCs may use internal APIs, registers or instructions. Communication protocols also include the `backend <-> frontend` channel. While the prototype idea is to use MQTT over the Linux TCP/IP stack, this may not be suitable for all the possible platforms;
    - ease its platform-agnosticism by abstracting away the implementation for any event processing and hardware resource. While Linux uses a signalling mechanism and provides APIs for timers, this is not the same case for µCs while being similar.
- **Event-based**:  the software will only work when needed and rest idle otherwise. An event-based system must be employed to wake up and instruct the server. This will work along the lines of event processing abstraction, so that ANY type of supported events can trigger the mechanism.

**Comment by roryort** [comment]
Understood :)

**Comment by roryort** [comment]
Closed due to merging of PR#16
