### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by Sevenarth** [healthyhomeuk/healthyhome#6]
- [ ] The user should be allowed to register its device;
- [ ] The user should be allowed to enable push notifications and:
    - [ ] opt in/out to receive alerts on worsening conditions with or without a schedule;
    - [ ] opt in/out to receive notices on improving conditions with or without a schedule;
    - [ ] opt in/out to receive overnight conditions in the morning;
    - [ ] opt in/out to receive daily updates on conditions change;
    - [ ] opt in/out to receive weekly updates on conditions change.
- [ ] The user should be able to see the overnight average, trend and spikes of the conditions;
- [ ] The user should be able to view a summary of and analyse the conditions (lower, upper spikes, trend and average) on a half-hourly, hourly, half-daily, daily, weekly, monthly basis, through a timeline;
- [ ] The user should be able to view a snapshot from the historical data;
- [ ] The user should be able to reset its device and clear all the saved data.

**Comment by roryort** [comment]
Closed with new website upload in `gh-pages` branch
